<?php

$countries = array(
	array("id"=>1,"name"=>"Wallis and Futuna"),
	array("id"=>2,"name"=>"Paraguay"),
	array("id"=>3,"name"=>"Belize"),
	array("id"=>4,"name"=>"Guam"),
	array("id"=>5,"name"=>"Botswana"),
	array("id"=>6,"name"=>"Indonesia"),
	array("id"=>7,"name"=>"Chile"),
	array("id"=>8,"name"=>"Cambodia"),
	array("id"=>9,"name"=>"Faroe Islands"),
	array("id"=>10,"name"=>"Bosnia and Herzegovina"),
	array("id"=>11,"name"=>"Greece"),
	array("id"=>12,"name"=>"United Arab Emirates"),
	array("id"=>13,"name"=>"Austria"),
	array("id"=>14,"name"=>"Kenya"),
	array("id"=>15,"name"=>"Åland Islands"),
	array("id"=>16,"name"=>"Dominica"),
	array("id"=>17,"name"=>"Palau"),
	array("id"=>18,"name"=>"Christmas Island"),
	array("id"=>19,"name"=>"Mauritania"),
	array("id"=>20,"name"=>"Azerbaijan"),
	array("id"=>21,"name"=>"Nepal"),
	array("id"=>22,"name"=>"Martinique"),
	array("id"=>23,"name"=>"Tanzania"),
	array("id"=>24,"name"=>"Bhutan"),
	array("id"=>25,"name"=>"Kyrgyzstan"),
	array("id"=>26,"name"=>"Palestine, State of"),
	array("id"=>27,"name"=>"Sri Lanka"),
	array("id"=>28,"name"=>"Gibraltar"),
	array("id"=>29,"name"=>"Sint Maarten"),
	array("id"=>30,"name"=>"Tunisia"),
	array("id"=>31,"name"=>"Swaziland"),
	array("id"=>32,"name"=>"Kenya"),
	array("id"=>33,"name"=>"Mexico"),
	array("id"=>34,"name"=>"South Africa"),
	array("id"=>35,"name"=>"Cuba"),
	array("id"=>36,"name"=>"Bermuda"),
	array("id"=>37,"name"=>"El Salvador"),
	array("id"=>38,"name"=>"Cameroon"),
	array("id"=>39,"name"=>"Canada"),
	array("id"=>40,"name"=>"Jamaica"),
	array("id"=>41,"name"=>"Seychelles"),
	array("id"=>42,"name"=>"Mali"),
	array("id"=>43,"name"=>"Mauritania"),
	array("id"=>44,"name"=>"Austria"),
	array("id"=>45,"name"=>"Myanmar"),
	array("id"=>46,"name"=>"Switzerland"),
	array("id"=>47,"name"=>"Guernsey"),
	array("id"=>48,"name"=>"Niue"),
	array("id"=>49,"name"=>"Mongolia"),
	array("id"=>50,"name"=>"Marshall Islands"),
	array("id"=>51,"name"=>"Pitcairn Islands"),
	array("id"=>52,"name"=>"Aruba"),
	array("id"=>53,"name"=>"Gibraltar"),
	array("id"=>54,"name"=>"Namibia"),
	array("id"=>55,"name"=>"Antigua and Barbuda"),
	array("id"=>56,"name"=>"Reunion"),
	array("id"=>57,"name"=>"Saint Helena, Ascension and Tristan da Cunha"),
	array("id"=>58,"name"=>"Bahrain"),
	array("id"=>59,"name"=>"Antigua and Barbuda"),
	array("id"=>60,"name"=>"Kyrgyzstan"),
	array("id"=>61,"name"=>"Angola"),
	array("id"=>62,"name"=>"Zambia"),
	array("id"=>63,"name"=>"Slovenia"),
	array("id"=>64,"name"=>"Israel"),
	array("id"=>65,"name"=>"Bermuda"),
	array("id"=>66,"name"=>"Gambia"),
	array("id"=>67,"name"=>"British Indian Ocean Territory"),
	array("id"=>68,"name"=>"Norway"),
	array("id"=>69,"name"=>"Ecuador"),
	array("id"=>70,"name"=>"Germany"),
	array("id"=>71,"name"=>"Jordan"),
	array("id"=>72,"name"=>"Suriname"),
	array("id"=>73,"name"=>"United States"),
	array("id"=>74,"name"=>"Timor-Leste"),
	array("id"=>75,"name"=>"Germany"),
	array("id"=>76,"name"=>"Falkland Islands"),
	array("id"=>77,"name"=>"Colombia"),
	array("id"=>78,"name"=>"Central African Republic"),
	array("id"=>79,"name"=>"Albania"),
	array("id"=>80,"name"=>"Mali"),
	array("id"=>81,"name"=>"Hungary"),
	array("id"=>82,"name"=>"Afghanistan"),
	array("id"=>83,"name"=>"Palestine, State of"),
	array("id"=>84,"name"=>"Tajikistan"),
	array("id"=>85,"name"=>"Saint Helena, Ascension and Tristan da Cunha"),
	array("id"=>86,"name"=>"Zimbabwe"),
	array("id"=>87,"name"=>"Madagascar"),
	array("id"=>88,"name"=>"Greece"),
	array("id"=>89,"name"=>"Benin"),
	array("id"=>90,"name"=>"Samoa"),
	array("id"=>91,"name"=>"Wallis and Futuna"),
	array("id"=>92,"name"=>"Faroe Islands"),
	array("id"=>93,"name"=>"Uzbekistan"),
	array("id"=>94,"name"=>"Bermuda"),
	array("id"=>95,"name"=>"Antarctica"),
	array("id"=>96,"name"=>"Virgin Islands, British"),
	array("id"=>97,"name"=>"French Guiana"),
	array("id"=>98,"name"=>"Austria"),
	array("id"=>99,"name"=>"Egypt"),
	array("id"=>100,"name"=>"Viet Nam")
);
